from __future__ import annotations

import logging
import os
from pathlib import Path

from alembic import command
from alembic.config import Config

logger = logging.getLogger(__name__)


def get_alembic_config(dsn: str | None = None) -> Config:
    project_root = Path(__file__).parent.parent.parent
    alembic_ini = project_root / "alembic.ini"

    if not alembic_ini.exists():
        raise FileNotFoundError(f"alembic.ini not found at {alembic_ini}")

    config = Config(str(alembic_ini))

    migrations_dir = project_root / "migrations"
    config.set_main_option("script_location", str(migrations_dir))

    if dsn:
        config.set_main_option("sqlalchemy.url", dsn)
    elif database_url := os.getenv("DATABASE_URL"):
        config.set_main_option("sqlalchemy.url", database_url)

    return config


def _convert_async_dsn_to_sync(dsn: str) -> str:
    return dsn.replace("+aiosqlite", "").replace("+asyncpg", "")


def run_migrations(dsn: str | None = None, offline: bool = False) -> None:
    if dsn:
        dsn = _convert_async_dsn_to_sync(dsn)

    config = get_alembic_config(dsn)

    os.environ["ALEMBIC_SKIP_LOGGING_CONFIG"] = "1"

    try:
        if offline:
            logger.info("Running migrations in offline mode (SQL generation)")
            command.upgrade(config, "head", sql=True)
            logger.info("Offline migrations completed successfully")
        else:
            logger.info("Running database migrations...")
            command.upgrade(config, "head")
            logger.info("Database migrations completed successfully")
    except Exception as e:
        logger.exception("Failed to run migrations: %s", e)
        raise
    finally:
        os.environ.pop("ALEMBIC_SKIP_LOGGING_CONFIG", None)


def create_migration(message: str, autogenerate: bool = True) -> None:
    config = get_alembic_config()

    try:
        if autogenerate:
            logger.info("Creating autogenerated migration: %s", message)
            command.revision(config, message=message, autogenerate=True)
        else:
            logger.info("Creating empty migration: %s", message)
            command.revision(config, message=message)
        logger.info("Migration created successfully")
    except Exception as e:
        logger.exception("Failed to create migration: %s", e)
        raise


def get_current_revision(dsn: str | None = None) -> str | None:
    from alembic.runtime.migration import MigrationContext
    from sqlalchemy import create_engine

    db_url = dsn or os.getenv("DATABASE_URL")
    if not db_url:
        raise ValueError("DATABASE_URL not provided")

    engine = create_engine(db_url.replace("+aiosqlite", "").replace("+asyncpg", ""))

    try:
        with engine.begin() as conn:
            context = MigrationContext.configure(conn)
            current = context.get_current_revision()
            return current
    finally:
        engine.dispose()


def check_migrations_needed(dsn: str | None = None) -> bool:
    from alembic.script import ScriptDirectory

    config = get_alembic_config(dsn)
    script = ScriptDirectory.from_config(config)

    try:
        current = get_current_revision(dsn)
        head = script.get_current_head()

        if current is None:
            logger.info("Database not initialized, migrations needed")
            return True

        if current != head:
            logger.info(
                "Current revision: %s, Head revision: %s - migrations needed", current, head
            )
            return True

        logger.info("Database is up to date (revision: %s)", current)
        return False
    except Exception as e:
        logger.warning("Could not check migration status: %s", e)
        return True
